# Dissecando uma variável
x = input('Digite qualquer coisa: ')
print('Tipo primitivo: {}'.format(type(x)))
print('')
print('É uma palavra? {}'.format(x.isalpha()))
print('')
print('É um número? {}'.format(x.isnumeric()))
print('')
print('É alfanumérico? {}'.format(x.isalnum()))
print('')
print('É maiúsculo? {}'.format(x.isupper()))
print('')
print('É minúsculo? {}'.format(x.islower()))
print('')
print('É somente espaços? {}'.format(x.isspace()))
print('')
print('Está capitalizado? {}'.format(x.istitle()))
