print('=*= MERCADINHO CEV =*=')
nome = input('Digite seu nome: ')
print('Olá, {}, seja bem-vindo!'.format(nome))
n = str(input('Digite o nome do produto: '))
print('Ótima escolha!!')
p = float(input('Digite o preço do produto: R$'))
vista = p - (p * 10 / 100)
parcelar = p + (p * 8 / 100)
print('{}, se deseja pagar à vista o preço do produto que antes era de R${:.2f},'.format(nome, p), end=' ')
print('agora com 10% de desconto será de R${:.2f}'.format(vista))
print('Se deseja pagar parcelado o preço do produto que antes era de R${:.2f},'.format(p), end=' ')
print('agora com 8% de aumento será de R${:.2f}'.format(parcelar))
